// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8vZgpkTAVveBWs1LKYlZFy3lq20zlF5Y',
    appId: '1:911840018429:web:3e468d846faca3c6dce394',
    messagingSenderId: '911840018429',
    projectId: 'prepflow-ai-f9926',
    authDomain: 'prepflow-ai-f9926.firebaseapp.com',
    storageBucket: 'prepflow-ai-f9926.firebasestorage.app',
    measurementId: 'G-01FMMYQSNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjTEzlFwSmMDhGz2TDBnvqsUoyS_GcTRk',
    appId: '1:911840018429:android:b13cd6097f6793a7dce394',
    messagingSenderId: '911840018429',
    projectId: 'prepflow-ai-f9926',
    storageBucket: 'prepflow-ai-f9926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxmnseLejpKwP_h52J9NYOl93_B0ItLPA',
    appId: '1:911840018429:ios:9c8b5af5c6275280dce394',
    messagingSenderId: '911840018429',
    projectId: 'prepflow-ai-f9926',
    storageBucket: 'prepflow-ai-f9926.firebasestorage.app',
    iosBundleId: 'com.example.prepflowAi',
  );
}
