import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../shared/widgets/app_button.dart';
import '../../../../shared/widgets/app_glass_card.dart';
import '../../../../shared/widgets/app_gradient_card.dart';
import '../../../../shared/widgets/app_chip.dart';
import '../../../../core/constants/app_spacing.dart';

class DashboardScreen extends ConsumerWidget {
  const DashboardScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Dashboard', style: TextStyle(fontWeight: FontWeight.w700)),
        centerTitle: true,
        automaticallyImplyLeading: false,
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Score Card
            AppGradientCard(
              child: Column(
                children: [
                   Text(
                    'Compatibility Match',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w700,
                      color: Theme.of(context).brightness == Brightness.dark 
                        ? Colors.white.withValues(alpha: 0.8) 
                        : Colors.black.withValues(alpha: 0.6),
                      letterSpacing: 0.1,
                    ),
                  ),
                  const SizedBox(height: 16),
                  const Text(
                    '88%',
                    style: TextStyle(
                      fontSize: 40,
                      fontWeight: FontWeight.w800,
                      color: Colors.white,
                    ),
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'Readiness: Excellent 🚀',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.w800,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
            
            AppSpacing.vLG,
            
            // Skill Gap Card
            AppGlassCard(
              onTap: () => context.go('/bank'), // Nav to Bank/Skill Gap
              child: const Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('📊 AI Skill Gap Insights', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
                  AppSpacing.vSM,
                  Text('Roadmap generated by comparing your Resume to the JD.', style: TextStyle(fontSize: 14)),
                  AppSpacing.vMD,
                  Row(
                    children: [
                      AppChip(label: 'Python', type: ChipType.strong),
                      AppSpacing.hSM,
                      AppChip(label: 'System Design', type: ChipType.weak),
                    ],
                  ),
                ],
              ),
            ),
            
            const Text('Up Next For You', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
            AppSpacing.vMD,
            
            // Bank Card
            AppGlassCard(
              onTap: () => context.go('/bank'),
              child: Row(
                children: [
                  Container(
                    width: 48,
                    height: 48,
                    decoration: BoxDecoration(
                      color: const Color(0xFF6366F1).withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(14),
                    ),
                    child: const Icon(Icons.forum_outlined, color: Color(0xFF6366F1)),
                  ),
                  AppSpacing.hMD,
                  const Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Smart Question Bank', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600)),
                        Text('Review 15 high-probability questions.', style: TextStyle(fontSize: 13)),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            
            AppButton(
              text: 'Prepare For A New Role',
              isSecondary: true,
              onPressed: () => context.go('/input'),
            ),
            const SizedBox(height: 100), // Spacer for bottom nav
          ],
        ),
      ),
    );
  }
}
